README.md
helpers/get-session-token.js
scripts/update-auth-trees/update-auth-trees.js
tests/helpers/get-session-token.test.js
tests/scripts/update-auth-trees.test.js

Realised we can get the cookie name from the existing API calls so removing the environment variable requirement

chore: remove cookie name environment variable

---

README.md
config/phase-0/internal-roles/admin.json
package-lock.json
package.json
scripts/update-internal-roles/index.js
scripts/update-internal-roles/update-internal-roles.js
tests/scripts/update-internal-roles.test.js

Added a script for creating internal roles with an example role configuration. This will be used for setting internal admin user permissions

feature: internal roles script

---

helpers/get-session-token.js
tests/helpers/get-access-token.test.js
tests/helpers/get-session-token.test.js

Added an additional call to the authenticate endpoint to skip the 2-step verification prompt

fix: handle mfa prompt when getting session token

---

config/applications/sdk-client.json.tpl

Added the 'email', 'profile' and 'phone' scopes to the OAuth2 SDK client application, so that the correct claims appear in the ID token for the UI to consume.

added extra scopes to add user claims in ID token

---

config/connectors/definitions/webfiling-auth-code.json
config/connectors/definitions/webfiling-users.json

Modified connection config to prevent `exceeded simultaneous SESSIONS_PER_USER limit` errors when connecting to the Dev database.

chore: reduce min/max connections

---

config/applications/sdk-client.json.tpl

small fix to include all required redirect URIs for the SDK client

updated redirect URIs for SDK client

---

.env.sample
.gitignore
config/am-scripts/scripts-content/oidc-claims-script.groovy
config/applications/idm-admin-client.json.tpl
config/applications/ig-oidc-client.json.tpl
config/applications/sdk-client.json.tpl
config/auth-trees/ch-webfiling.json
config/services/oauth2-provider.json.tpl
config/services/validation.json
helpers/cli-options.js
index.js
scripts/update-applications.js
scripts/update-services.js
tests/scripts/update-applications.test.js

Initial configuration to support WebFiling journey:
- creation of OIDC client to be used by IG for authN (with default ACR value of EWF journey ID)
- config of Oauth2 provider service to include ACR mapping and new custom login URL
- new basic CHWebFiling journey (will be expanded later)
- new URLs added to validation service (will be parametrised later)
- hardcoding of ID Token claims in the OIDC claims script (will be modified later)

EWF oidc config

---

config/auth-trees/ch-webfiling.json

- added missing 'Identify Existing User' node in EWF journey, to make sure we fetch the current user info after skipping login 

added missing node in EWF journey

---

scripts/update-auth-trees.js

Auth tree updates were failing due to too many requests. 

fix: run auth tree updates sequentially

---

config/am-scripts/scripts-config.json
config/am-scripts/scripts-content/ch-email-consent-change.js
config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-invite-user-send-email.js
config/am-scripts/scripts-content/ch-remove-user-prompt-confirmation.js
config/auth-trees/ch-manage-email-consent.json
config/auth-trees/ch-onboarding.json
config/auth-trees/ch-registration-verify.json
config/auth-trees/ch-webfiling-login.json
config/auth-trees/ch-webfiling.json
config/managed-objects/alpha-user.json

- added 'Manage Email Consent' journey with 'consent collection' and 'change consent' modes
- changed Registration, EWF Login and Onboarding trees to include the 'Manage Email Consent'
- changed alpha_user definition to add preferences description
- [ x ] managed-objects

email consent

---

config/applications/ig-oidc-client.json.tpl
config/services/session.json

Set session timeout and access token lifetime to 40 minutes.

feat: session timeout

---

.gitignore
helpers/cli-options.js
helpers/fidc-get.js
index.js
package-lock.json
scripts/get-auth-tree.js
scripts/index.js

Added an additional CLI operation to get the JSON representation of an AM Auth Tree (Journey)
update-fidc get-auth-tree ... -atn CHWebFiling

Added support for getting an AM Auth Tree JSON payload from the FIDC Server

---

.gitignore
config/applications/ig-oidc-client.json.tpl

Added additional callback endpoint (same as existing one) but without the 443 port.

Added additional callback for oidc_client to support non-443 endpoint

---

scripts/update-scripts.js

Throw an exception if the AM Script has a blank, or undefined, name prior to PUT call to FIDC
- [ X] am-scripts

Ensure that AM script has a non-blank name on update

---

scripts/update-managed-objects.js
scripts/update-scripts.js
tests/helpers/file-filter.test.js
tests/scripts/update-managed-objects.test.js
tests/scripts/update-scripts.test.js

Updated tests to increase unit test coverage.
Still have a couple of issues I need to resolve that work OK when run in Debug Mode in Webstorm, but not on the command line when running 'npm test' but this is only related to when an exception is thrown so is low priority.
- [ X] am-scripts
- [ X] managed-objects

Increase unit test coverage

---

config/agents/ig-agent.json.tpl

The Agent password in the template file was specified incorrectly, meaning that password from the CLI was ignored and it was always being set as the literal string "{PASSWORD}" in FIDC.

Fix for merge variable for Agent password

---

config/am-scripts/scripts-library/ch-library-functions.js
scripts/update-scripts.js

Added some obfuscation functions to the library to support CH styles (as confirmed with Sophie).
Emails will always be "first char + 5 asterisks"
Phone Numbers will always be "asterisks + last 4 chars, with spaces in key places for accessibility"

Email / Phone Number obfuscation

---

config/am-scripts/scripts-library/ch-library-functions.js

Fix issue if "_scriptName" not defined in the calling AM script.

Support for logging at different levels - fix for missing var

---

scripts/update-scripts.js

Revert back to Standard JS formatting to fix Concourse linting issues

Revert back to Standard JS formatting to fix Concourse linting issues

---

config/am-scripts/scripts-content/ch-callback-general-error.js
config/auth-trees/ch-multi-factor-generic.json

* As requested by CH it only allows 5 attempts at resending the OTP before erroring

idam-1002/Allow 5 resends of OTP before erroring

---

config/am-scripts/scripts-content/ch-mfa-sub-flow-setup.js
config/auth-trees/ch-update-email.json

* Change to MFA Generic OTP setup script to force flow to always use EMAIL for OTP sending (as it's to enforce the check of a valid email)
* Change to the Auth Tree for Change Email Address to use the generic OTP flow 

idam-921/Support for resending OTP via email

---

config/idm-endpoints/scripts-content/scrs.js

* Back to original Harmonia format for emails list service
* Force all emails to use "en" language as per CH decision

idam-837/Change SCRS emails to EN and use original response format

---

config/am-scripts/scripts-content/ch-login-error-message.js

* Add unknown email to logging and payload response so that it's easier to see the user who tried to login but was not found in logs

idam-1035/add unknown email to logging and payload response

---

bash-scripts/add_concourse_user.sh
bash-scripts/get_idm_access_token.sh

* Remove OAuth2 client requirements as params
* Remove Realm requirements as params
* Modify Add Concourse User script to pass less params to get IDM token

idam-1039/remove unused parameters

---

config/auth-trees/settings/tree-auth.json
scripts/update-auth-trees.js

* Support the modification of the JWT for Auth Journeys via config (set to 30 mins instead of default 5 mins)

idam-1042/increase jwt timeout to 30 minutes

---

config/connectors/mappings/alphaUser_webfilingUser.json
config/connectors/mappings/cleanup_FIDC_companies.json
config/connectors/mappings/cleanup_FIDC_users.json

- temporarily setting the SOURCE_MISSING behaviour to EXCEPTION action instead of DELETE (as it has side effects when combined with cleanup mappings recons)
- adding users cleanup mappings for Staging
- adding companies cleanup mappings for Staging

adding cleanup mappings for Staging

---

config/am-scripts/scripts-content/ch-reset-password-clear-parameters.js

* Change status of user back to "active" to cover off cases where the user was created by SCRS, didn't get the link to activate (went to Spam etc) and then goes through the Password Reset route. Currently, if the user is still "inactive" then they get all the way through the journey successfully and right at the end get told they are signed out, which isn't very good.

idam-1060/reset accountStatus to active after reset password completes

---

config/am-scripts/scripts-content/ch-invite-user-send-email.js
config/am-scripts/scripts-content/ch-join-company-create-relationship.js
config/am-scripts/scripts-content/ch-password-reset-send-email.js
config/am-scripts/scripts-content/ch-registration-send-email.js
config/am-scripts/scripts-content/ch-remove-user-send-email.js
config/am-scripts/scripts-content/ch-send-mfa-email.js
config/am-scripts/scripts-content/ch-send-mfa-sms.js
config/am-scripts/scripts-content/ch-webfiling-check-for-company-assoc-status.js
config/am-scripts/scripts-content/ch-webfiling-prompt-for-link-confirmation.js
config/am-scripts/scripts-content/ch-webfiling-store-lang-in-session.js
config/auth-trees/ch-update-email.json
config/auth-trees/ch-update-phone-number.json
config/auth-trees/ch-webfiling-complete-profile.json
config/auth-trees/ch-webfiling-login.json

* Remove duplicated code in terms of getSelectedLanguage() functions
* Replace usages with call to library function
* Untick any 'Save value to user' checkboxes on Retry Decision nodes in Journeys

Idam 1074/use getSelectedLanguage function from library and turn off save of retry state to user 

---

config/auth-trees/ch-create-company-association.json
config/auth-trees/ch-credential-validation.json
config/auth-trees/ch-login.json
config/auth-trees/ch-update-legacy-password.json
config/auth-trees/ch-update-password.json
config/auth-trees/ch-webfiling.json

* modify retry limit decision nodes to not save to user state

idam-1074/modify retry limit decision nodes to not save to user state

---

config/connectors/mappings/chsMongoCompanyProfile_alphaOrg.json
config/connectors/schedules/ds-backup.json

- added condition to map 'england' and 'wales' companies to EW jurisdiction
- temporarily disabled the DSbackup scheduled recon

fix to map Welsh companies to the 'EW' jurisdiction in FIDC

---

config/am-scripts/scripts-content/ch-mfa-sub-flow-setup.js
config/auth-trees/ch-multi-factor-generic.json
config/auth-trees/ch-password-reset.json
config/auth-trees/ch-registration-start.json
config/auth-trees/ch-webfiling-complete-profile.json
config/auth-trees/ch-webfiling-login.json

* Roll out the use of the generic OTP subflow across other journeys
config/am-scripts/scripts-content/ch-mfa-sub-flow-setup.js
config/auth-trees/ch-password-reset.json
config/auth-trees/ch-registration-start.json
config/auth-trees/ch-webfiling-complete-profile.json
config/auth-trees/ch-webfiling-login.json

Idam 923/use generic otp subflow

---

.gitignore
config/managed-users/admin-client-test.json.tpl
scripts/update-managed-users.js

* Add AdminClientTest user as a managed user for automated tests

idam-1040/add client admin test user for automated tests

---

config/auth-trees/ch-webfiling-login.json

* Remove progressive profiling sub-journey as not required, and was causing intermittent blank pages to be shown at login (every 3 attempts) as there was no matching UI stage (as the pageNode in the journey had a blank stage name) 

idam-1124/Remove progressive profiling sub-journey as not required

---

config/am-scripts/scripts-content/ch-callback-to-capture-otp-response.js

* Add error to PageProps if OTP code is invalid

idam-1132/Fix error shown if invalid OTP

---

config/am-scripts/scripts-content/ch-scrs-validate-params.js
config/connectors/mappings/cleanup_FIDC_users.json
config/managed-users/tree-service-user.json.tpl
config/password-policy/password-policy.json
tests/scripts/update-managed-users.test.js

* Change `.com` users to be `.gov.uk`
* Change simple passwords to be more complex
* Modify tree-service-user password
* Modify ESVs to match

Idam 1114/increase complexity change gov uk

---

config/am-scripts/scripts-content/ch-invite-user-send-email.js
config/am-scripts/scripts-content/ch-registration-send-email.js

* Remove use of 'origin' request header to get Base URL, prefering instead the property from ESV

idam-1177/Remove use of request header origin in AM scripts

---

config/am-scripts/scripts-content/ch-update-pwd-load-new-pwd-for-patch.js
config/auth-trees/ch-registration-verify.json
config/auth-trees/ch-update-password.json

* Set password in session after changing it to ensure that the session has the most up to date value

idam-1316/Set password in session after changing it

---

config/am-scripts/scripts-content/oauth2-token-mod.groovy

Added the mappings for all the scopes mentioned in [here](https://companieshouse.atlassian.net/wiki/spaces/Arch/pages/1334771713/API+Filing+Service+Designs+3rd+Parties+and+CH)
There were a few dynamic values that require a regex to be used in order to get the value out the scope and returned in the permissions.
It can probably be improved but as it's a PoC this can do for now without obfuscating some of the mapping logic.

Token mappings

---

config/connectors/definitions/webfiling-users.json

Updated `maxActive` and `initialSize` parameters to use ESV values
Reverted Pool config options previously updated

Set initialSize & maxActive to esv values

---

config/am-scripts/scripts-content/ch-callback-to-capture-otp-response.js

Update OTP journey to include a link for SMS OTP method

feat: add option to send sms via link

---

config/connectors/definitions/inactive-user.json
config/connectors/mappings/inactiveUser_alphaUser.json

Added connector to read CSV of users that need to have their accountStatus set to inactive.
Added mapping which uses the connector mentioned above to run a recon process to deactivate the users.

IDAM 1596: Reconcilation for inactivating users

---

config/connectors/remote-servers.json

Due to issues seen recently with nightly syncs and Forgerock RCS connections to the users and companies databases, a ticket was raised with Forgerock for advise on the errors we were seeing in the RCS and IDM logs. 
In response, Forgerock have advised us to add this additional config for maxMessageSize to our FIDC config. 
>We can try the following to see if there is any difference, within the openicf connector there is max message size - so how much data it can transfer across, you would need to just set this value to    "maxMessageSize" : 102400
I am adding in this additional config in order to see if this resolves the issues we have been seeing with the RCS connections. 

added suggested maxMessageSize config

---

config/am-scripts/scripts-content/ch-invalidate-user-sessions.js
config/auth-trees/ch-update-password.json
config/variables-secrets/secrets.json
config/variables-secrets/variables.json

Script added to invalidate user sessions. ESVs added for script to use service account. Auth-tree modified to incorporate the new node that uses the script and create the necessary connections to the surrounding nodes. A node was removed. 

fix: persistent session vulnerability

---

config/idm-endpoints/scripts-config.json

This is a bug fix suggested to resolve an issue with the FIDC scripts preventing an upgrade on the Forgerock backend.  This involved amended the lt operator to the lte one and amending the days to accomodate this change.

fix: bug fix for FIDC upgrade

---

config/variables-secrets/secrets.json

Large secrets, as the ones required by FIDC service account private keys, are not updating successfully on FIDC when they are released via the pipeline.
Here, I have
For this reason, and until ForgeRock solve this problem, we will need to update the esv-service-account-privatekey manually.

fix: remove service acc private key secret

---

config/idm-endpoints/scripts-config.json

As advised by ForgeRock, changes made to _scripts-config.json_ file to replace the `lt` ... `7d` statements for `lte` ... `8d`
This has been done to facilitate ForgeRock's update of FIDC from the 2023 version to a newer 2024 version. ForgeRock have advised that the `lt` operator was the reason for the updates to fail.

fix: replace lt operator for lte

---

scripts/update-cors.js
tests/scripts/update-cors.test.js

Updates to the global CORS configuration is no longer working with the changes introduced to session tokens (https://github.com/companieshouse/forgerock-cloud-config/pull/537). This PR removes the global CORS from the update command as these are unlikely change.

chore: remove global cors config

---

.env.sample
README.md
helpers/fidc-get.js
helpers/fidc-post.js
helpers/fidc-request.js
helpers/get-service-account-token.js
helpers/get-signed-jwt.js
index.js
package-lock.json
package.json
scripts/restart-fidc.js
scripts/update-agents.js
scripts/update-applications.js
scripts/update-cors.js
scripts/update-esv-and-restart.js
scripts/update-internal-roles.js
scripts/update-managed-users.js
scripts/update-secrets.js
scripts/update-user-roles.js
scripts/update-variables.js
tests/scripts/update-agents.test.js
tests/scripts/update-applications.test.js
tests/scripts/update-cors.test.js
tests/scripts/update-internal-roles.test.js
tests/scripts/update-managed-users.test.js
tests/scripts/update-user-roles.test.js

The pipeline is getting a 403 error when attempting to update the dynamic config for Staging. To resolve this I have changed the dynamic config to use a Service Account for authentication. 

fix: update dynamic config to use service account auth

---

config/variables-secrets/secrets.json
package.json
scripts/update-secrets.js

Service Account JSON is too large for AWS parameter store so cannot be set in the pipeline easily. This change allows setting multiple JSON environment variables that will be merged for the final secret.

Update service account esv using multiple json inputs

---

config/connectors/definitions/archived/mongodb-api-client-keys
config/connectors/definitions/archived/mongodb-auth-code.json
config/connectors/definitions/archived/mongodb-roles.json
config/connectors/definitions/archived/mongodb-users.json
config/connectors/definitions/mongodb-companies.json
config/connectors/definitions/mongodb-forgerock-data.json

Reverse MongoDB connector upgrade to a known good version, as 1.5.20.22 was showing compatibility issues with MongoDB v6. Reversed to 1.5.20.0

fix: reverse mongo db connector upgrade

---

config/idm-endpoints/scripts-content/bulkOperation.js

Add a custom endpoint `bulkOperation` to support bulk update requests. This is related to the Uppercase Emails Incident [CS002060027](https://envision.service-now.com/sn_customerservice_case.do?sys_id=8e295af61b2682d4b96ca6c8ec4bcb2f&sysparm_view=case&sysparm_record_target=sn_customerservice_case&sysparm_record_row=10&sysparm_record_rows=11&sysparm_record_list=active%3Dtrue%5Eassignment_groupDYNAMICd6435e965f510100a9ad2572f2b47744%5EconsumerISEMPTY%5EORDERBYstate)

Add bulk operation endpoint

---

config/connectors/definitions/archived/mongodb-api-client-keys
config/connectors/definitions/archived/mongodb-auth-code.json
config/connectors/definitions/archived/mongodb-roles.json
config/connectors/definitions/archived/mongodb-users.json
config/connectors/definitions/mongodb-companies.json
config/connectors/definitions/mongodb-forgerock-data.json

fix: revert back mongo connector incident CS002523005

---

config/connectors/mappings/webfilingUser_alphaUser.json

Add a correlation query to the webfilingUser_alphaUser mapping. If any users are missing a link to an existing EWF record, they will identified by the correlation query, and a new link will be created.

Add a correlation query to webfilingUser_alphaUser mapping

---

config/connectors/definitions/archived/mongodb-api-client-keys
config/connectors/definitions/archived/mongodb-auth-code.json
config/connectors/definitions/archived/mongodb-roles.json
config/connectors/definitions/archived/mongodb-users.json
config/connectors/definitions/mongodb-companies.json
config/connectors/definitions/mongodb-forgerock-data.json

Upgrade all MongoDB RCS connectors to **1.5.20.22**.

Upgrade RCS connectors to 1.5.20.22 #2

---

config/connectors/definitions/archived/mongodb-api-client-keys
config/connectors/definitions/archived/mongodb-auth-code.json
config/connectors/definitions/archived/mongodb-roles.json
config/connectors/definitions/archived/mongodb-users.json
config/connectors/definitions/mongodb-companies.json
config/connectors/definitions/mongodb-forgerock-data.json

This reverts commit c0c99ecf71040918bc725cd29c67451015d94c3a.
Back to old connector due to 500 errors in Dev

Revert "Upgrade RCS connectors to 1.5.20.22 #2"

---

config/connectors/schedules/auth-codes.json
config/connectors/schedules/companies.json
config/connectors/schedules/ds-backup.json
config/connectors/schedules/users.json

Set `recoverable=true` for all reconciliation schedules. This parameter specifies whether jobs that have failed mid-execution should be recovered. It is false by default. We can enable this to improve the performance of our reconciliations, as we are seeing random database connection failures that are affecting overnight runs.

Set recoverable=true for all schedules

---

config/connectors/mappings/webfilingUser_alphaUser.json

Add a transformation step to the mapping `webfilingUser_alphaUser` to lowercase the value for `EMAIL`.

Mapping transformation for uppercase emails

---

config/connectors/definitions/archived/mongodb-auth-code.json
config/connectors/definitions/archived/mongodb-roles.json
config/connectors/definitions/archived/mongodb-users.json
config/connectors/definitions/archived/webfiling-auth.json
config/connectors/definitions/mongodb-companies.json
config/connectors/definitions/mongodb-forgerock-data.json
config/connectors/definitions/webfiling-auth-code.json
config/connectors/definitions/webfiling-users.json

- Upgrade WebfilingAuthCode Table Connector to 1.5.20.27
- Upgrade WebfilingUser Table Connector to 1.5.20.27
- Upgrade WebfilingAuth Table Connector to 1.5.20.27
- Upgrade CHSAuthCode MongoDB Connector to 1.5.20.27
- Upgrade CHSRoles MongoDB Connector to 1.5.20.27
- Upgrade CHSUser MongoDB Connector to 1.5.20.27

Upgrade RCS connectors to 1.5.20.27

---

config/connectors/definitions/mongodb-companies.json
config/connectors/definitions/mongodb-forgerock-data.json
config/connectors/definitions/webfiling-auth-code.json
config/connectors/definitions/webfiling-users.json

Set RCS connector timeout settings back to previous values as connectors are timing out:
```
Mar 05, 2025 11:54:03 AM INFO  org.mongodb.driver.cluster: No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=pl-0-eu-west-2.ueium.mongodb.net:1029, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: Connect timed out}}, ServerDescription{address=pl-0-eu-west-2.ueium.mongodb.net:1028, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: Connect …
```

Revert connection timeout settings

---

config/am-scripts/scripts-content/ch-check-user-source.js

Use the `ci` (case-insensitive) operator instead of `eq` (equals). This will translate to the following SQL query that uses function-based indexing: 
`SELECT ... FROM CUSTOMER_VIEW WHERE LOWER(EMAIL) = LOWER(?)`

Change SQL query to use function-based indexing
