companieshouse/forgerock-cloud-config

config/phase-0/auth-trees/registration.json
config/phase-0/consent/terms-and-conditions.json
package-lock.json
package.json
scripts/update-scripts/update-scripts.js
scripts/update-terms-and-conditions/index.js
scripts/update-terms-and-conditions/update-terms-and-conditions.js
tests/scripts/update-scripts.test.js
tests/scripts/update-terms-and-conditions.test.js

- Added a script for updating the terms and conditions with an example role configuration.
- Added an initial registration auth tree
- Added pre-commit hook for lint and test

feature: t&c script and registration auth tree

---

config/phase-0/am-scripts/scripts-config.json
config/phase-0/am-scripts/scripts-content/ch-create-notify-jwt.js
config/phase-0/am-scripts/scripts-content/ch-send-registration-email.js

adding scripts for getting a token to call Gov Notify REST api, and a sample script using the token to call notify API

scripts for getting a token to call Gov Notify REST api

---

config/phase-0/connectors/mappings/mongodb-users.json
scripts/update-connectors/index.js
scripts/update-connectors/update-connector-mappings.js
tests/scripts/update-connector-mappings.test.js

Script for configuration connector mappings

feat: connector mapping script

---

.gitignore
README.md
config/phase-0/applications/sdk-client.json
config/phase-0/cors/cors-config.json
package.json
scripts/update-applications/index.js
scripts/update-applications/update-applications.js
tests/scripts/update-applications.test.js

Script to update applications for the SDK Client application required by the UI

feature: update applications script

---

config/phase-0/connectors/definitions/mongodb.json

Upgrade connector to v1.5.19.5

chore: connector upgrade

---

.gitignore
README.md
config/phase-0/services/oauth2-provider.json.tpl
helpers/replace-sensitive-values.js
package-lock.json
package.json
scripts/update-services/index.js
scripts/update-services/update-services.js
tests/helpers/replace-sensitive-values.test.js
tests/scripts/update-services.test.js

New script for updating AM services. A config file for the OAuth2 Provider has been added. A new helper function has also been added to replace sensitive values in the config files.

feat: update services script

---

config/phase-0/connectors/definitions/mongodb.json

Use account collection for user connector

chore: update connector to use account collection

---

config/phase-0/am-scripts/scripts-content/ch-password-reset-send-email.js
config/phase-0/am-scripts/scripts-content/ch-password-reset-text-sent.js
config/phase-0/am-scripts/scripts-content/ch-registration-send-email.js
config/phase-0/am-scripts/scripts-content/ch-registration-verify-token.js
config/phase-0/am-scripts/scripts-content/ch-send-mfa-sms.js

improved logging
reformatted scripts
added callbacks for Notify notificationId after both email and SMS sending

added callbacks for Notify notificationId

---

config/connectors/definitions/mongodb-auth-code.json
config/connectors/definitions/mongodb-companies.json
config/connectors/definitions/mongodb-roles.json
config/connectors/definitions/mongodb.json

Updating the remote host to the failover group now works

chore: update connectors to use failover group

---

config/auth-trees/ch-password-reset.json
config/auth-trees/ch-registration-start.json
config/auth-trees/login.json

added Retry Limit node on Registration and Pwd Reset trees, added coordinates on Login tree

updates to reg/pwdreset trees

---

config/am-scripts/scripts-content/ch-create-notify-jwt.js
config/am-scripts/scripts-content/ch-phone-number-entered.js
config/am-scripts/scripts-content/ch-send-mfa-sms.js

upgraded Create JWT for Notify script, to included non-deprecated classes
re-enabled MFA on registration

Fixes to registration

---

config/am-scripts/scripts-config.json
config/am-scripts/scripts-content/ch-callback-prompt-for-company-info.js
config/am-scripts/scripts-content/ch-check-for-session.js
config/am-scripts/scripts-content/ch-create-notify-jwt.js
config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-get-idm-access-token.js
config/am-scripts/scripts-content/ch-join-company-create-relationship.js
config/auth-trees/ch-create-company-association.json

- adding scripts for company lookup
- adding scripts for company association
- adding main company association tree including the above
- adding documentation on top of the scripts code to define input/output data, outcomes and callbacks
- renaming one script

adding logic for company lookup and company association

---

config/am-scripts/scripts-content/ch-join-company-create-relationship.js
config/am-scripts/scripts-content/ch-join-company-prompt-for-company-authcode.js

improved error handling in auth code screen
refactored code for readability

improved error handling

---

config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-join-company-create-relationship.js
config/am-scripts/scripts-content/ch-join-company-prompt-for-company-authcode.js
config/am-scripts/scripts-content/ch-join-company-prompt-for-company-no.js
config/am-scripts/scripts-content/ch-join-company-wrong-code-error-message.js

- improved error handling to included field names
- conditional adding of error JSON props callback

Coreate Company Association: improved error handling

---

config/am-scripts/scripts-content/ch-fetch-company-info.js

- fix 'no auth code defined' error handling
- fixed formatting for the whole file

fix 'no auth code defined' error handling

---

config/am-scripts/scripts-content/ch-create-notify-jwt.js
config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-join-company-create-relationship.js
config/am-scripts/scripts-content/ch-join-company-prompt-for-company-authcode.js
config/am-scripts/scripts-content/ch-join-company-prompt-for-company-no.js
config/am-scripts/scripts-content/ch-join-company-wrong-code-error-message.js
config/am-scripts/scripts-content/ch-password-reset-text-sent.js
config/am-scripts/scripts-content/ch-registration-send-email.js
config/am-scripts/scripts-content/ch-send-mfa-sms.js
config/am-scripts/scripts-content/ch-validate-credential.js

- improved error handling to use params, refactor and reformat

improved error handling to use params, refactor and reformat

---

config/am-scripts/scripts-config.json
config/am-scripts/scripts-content/ch-callback-max-retry-limit.js
config/am-scripts/scripts-content/ch-check-for-session.js
config/am-scripts/scripts-content/ch-create-notify-jwt.js
config/am-scripts/scripts-content/ch-password-reset-send-email.js
config/am-scripts/scripts-content/ch-password-reset-text-sent.js
config/am-scripts/scripts-content/ch-password-reset-verify-token.js
config/am-scripts/scripts-content/ch-registration-error-user-exists.js
config/am-scripts/scripts-content/ch-registration-send-email.js
config/am-scripts/scripts-content/ch-registration-verify-token.js
config/am-scripts/scripts-content/ch-send-mfa-email.js
config/am-scripts/scripts-content/ch-update-pwd-check-password-policy.js
config/am-scripts/scripts-content/ch-update-pwd-input-collector.js
config/am-scripts/scripts-content/ch-update-pwd-password-error-message.js
config/auth-trees/ch-create-company-association.json
config/auth-trees/ch-password-reset.json
config/auth-trees/ch-update-password.json

error handling the 'max retries' error
added token for translations where missing
refactor parts of the code where needed
reformatting

error handling stuff

---

config/connectors/definitions/ds-backup.json
config/connectors/mappings/ds-backup.json
config/connectors/mappings/ds-restore.json
config/connectors/schedules/ds-backup.json
index.js
scripts/index.js
scripts/update-connector-schedules.js
tests/scripts/update-connector-schedules.test.js

Added DS backup connector definition, mappings and schedule.
Currently only backup for users as Organization is still WIP.

feat: ds-backup config

---

config/am-scripts/scripts-content/ch-callback-login-error.js
config/am-scripts/scripts-content/ch-login-error-message.js
config/am-scripts/scripts-content/ch-login-soft-lock-check.js
config/am-scripts/scripts-content/ch-login-soft-lock-increment-counter.js
config/auth-trees/ch-login.json

- improved error messages for soft lock
- changes fieldName/anchor for soft lock errors (to point at username field)
- removed unused outcome form increment counter node in CHLogin tree

Few changes for Soft Lock

---

.gitignore
config/am-scripts/scripts-content/ch-callback-login-error.js
config/am-scripts/scripts-content/ch-check-password-status.js
config/am-scripts/scripts-content/ch-invite-user-prompt-for-email.js
config/am-scripts/scripts-content/ch-join-company-prompt-for-company-authcode.js
config/am-scripts/scripts-content/ch-join-company-prompt-for-company-no.js
config/am-scripts/scripts-content/ch-login-soft-lock-check.js
config/am-scripts/scripts-content/ch-login-soft-lock-reset-counter.js
config/am-scripts/scripts-content/ch-update-phone-input-collector.js
config/am-scripts/scripts-content/ch-update-pwd-input-collector.js
config/idm-endpoints/scripts-content/companyauth.js

- added logic to store pwd in shared state before call to subtree, transientState restore in subtree and and consequent sharedState cleanup 
- fixed boolean expressions in several files
- improved logging

bugfix for IDAM-485 - restored password from sharedState in subtree

---

config/am-scripts/scripts-config.json
config/am-scripts/scripts-content/ch-login-error-message.js
config/am-scripts/scripts-content/ch-login-input-check.js
config/auth-trees/ch-login.json
config/auth-trees/ch-webfiling-login.json

- added extra script to manage credentials format check (invalid email format, missing username, missing password)
- improved logic to display correct error 
- changed CHLogin and CHWebFiling-Login journeys accordingly

Improved login error handling

---

config/am-scripts/scripts-content/ch-webfiling-store-pwd-in-session.js
config/am-scripts/scripts-content/oidc-claims-script.groovy

- changed claims script to read infos from session
- amended pwd storage in session within EWF journey

OIDC claims script updates

---

config/am-scripts/scripts-content/oidc-claims-script.groovy
config/applications/ig-oidc-client.json.tpl

- defined extra 'webfiling' scope in OIDC client
- added extra EWF claims only for new scope

OIDC changes for EWF

---

.github/pull_request_template.md

Add a PR template with checkboxes for require FIDC updates.

chore: add initial pr template

---

config/connectors/definitions/webfiling-users.json

Updated WebFiling users connector to use right view name

---

config/connectors/definitions/webfiling-users.json

Updated WebFiling users connector to use correct (non plural) view name

---

config/connectors/definitions/ds-backup.json
config/connectors/definitions/webfiling-auth-code.json
config/connectors/definitions/webfiling-users.json

Update connector definitions to match the RCS version.

chore: increase rcs version

---

config/connectors/definitions/mongodb-auth-code.json

Disable CHSAuthCode connector

---

config/am-scripts/scripts-content/ch-update-pwd-check-password-policy.js

Attach failed policy requirements to error message

---

config/am-scripts/scripts-content/ch-webfiling-update-profile.js
config/auth-trees/ch-webfiling-complete-profile.json
config/auth-trees/ch-webfiling.json

- integrated CompleteProfile subtree in EWF tree
- refactored input collector script to allow constant number of callbacks
- removed session check nodes from subtree

EWF complete profile integration in EWF

---

config/am-scripts/scripts-content/ch-create-notify-jwt.js
config/am-scripts/scripts-content/ch-invite-user-send-email.js
config/am-scripts/scripts-content/ch-password-reset-send-email.js
config/am-scripts/scripts-content/ch-registration-send-email.js
config/am-scripts/scripts-content/ch-send-mfa-email.js
config/am-scripts/scripts-content/ch-send-mfa-sms.js

- added new templates in Notify array
- adapted journeys to read template with language prefix (with hardcoded EN for now)
- general reformatting

multi-language email support changes

---

config/password-policy/password-policy.json

Update password policy to match CH policy

---

config/connectors/mappings/mongodb-users.json
config/connectors/mappings/webfiling-users.json

Updated user mappings to reflect updates to required syncs

---

config/connectors/mappings/mongodb-organizations.json

Check for null before setting values

---

config/connectors/mappings/mongodb-organizations.json

Remap jurisdictions to be as per EWF

---

config/am-scripts/scripts-content/ch-callback-otp-not-valid.js
config/am-scripts/scripts-content/ch-callback-show-phone-or-mail.js
config/am-scripts/scripts-content/ch-password-reset-text-sent.js
config/am-scripts/scripts-content/ch-update-name-input-collector.js
config/auth-trees/ch-webfiling-login.json

- fixed index of callbacks
- removed duplicate node in EWFLogin tree
- general formatting, fix documetation

callback fixes

---

config/connectors/mappings/mongodb-organizations.json

Fix NI check

---

config/am-scripts/scripts-config.json
config/am-scripts/scripts-content/ch-callback-otp-not-valid.js
config/am-scripts/scripts-content/ch-callback-update-phone-show-number.js
config/am-scripts/scripts-content/ch-check-for-session.js
config/am-scripts/scripts-content/ch-invite-user-create-pending-relationship.js
config/am-scripts/scripts-content/ch-invite-user-fetch-company.js
config/am-scripts/scripts-content/ch-invite-user-prepare-user-onboarding.js
config/am-scripts/scripts-content/ch-invite-user-prompt-for-email.js
config/am-scripts/scripts-content/ch-invite-user-respond-invite.js
config/am-scripts/scripts-content/ch-invite-user-send-email.js
config/am-scripts/scripts-content/ch-login-input-check.js
config/am-scripts/scripts-content/ch-login-soft-lock-check.js
config/am-scripts/scripts-content/ch-login-soft-lock-reset-counter.js
config/am-scripts/scripts-content/ch-onboarding-pwd-input-collector.js
config/am-scripts/scripts-content/ch-onboarding-verify-token.js
config/am-scripts/scripts-content/ch-password-reset-send-email.js
config/am-scripts/scripts-content/ch-password-reset-verify-token.js
config/am-scripts/scripts-content/ch-registration-verify-token.js
config/am-scripts/scripts-content/ch-require-mfa-check.js
config/am-scripts/scripts-content/ch-update-pwd-check-password-policy.js
config/am-scripts/scripts-content/ch-webfiling-check-for-company-assoc-status.js
config/am-scripts/scripts-content/ch-webfiling-prompt-for-company-no.js
config/am-scripts/scripts-content/ch-webfiling-prompt-for-link-confirmation.js
config/am-scripts/scripts-content/ch-webfiling-update-profile.js
config/auth-trees/ch-onboarding.json
config/auth-trees/ch-webfiling-complete-profile.json

- scripts and tree definition for onboarding journey
- fixed reset pwd token timeout
- improved error handling
- renamed OTP stage name
- 

onboarding journey

---

config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-webfiling-prompt-for-company-no.js
config/auth-trees/ch-webfiling.json

- added logic to go back to company selection
- improved error handling in script for fetching company info

logic to go back to company selection in EWF journey

---

config/am-scripts/scripts-content/ch-update-pwd-check-password-policy.js

reset error messages in case of successful pwd policy check
- [x ] am-scripts

reset error messages in case of successful pwd policy check

---

config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-webfiling-prompt-for-company-no.js
config/auth-trees/ch-create-company-association.json

- added jurisdiction check to EWF journey
- added the 'other' outcome to company info fetch in Company Association journey
- 

added jurisdiction check to EWF journey

---

config/am-scripts/scripts-content/ch-update-phone-input-collector.js

- Update the error definition to target the correct callback id

Update target for invalid credentials error

---

config/am-scripts/scripts-content/ch-webfiling-prompt-for-company-no.js
config/auth-trees/ch-webfiling.json

- changes to EWF journey to read company no/jurisdiction from query parameters (skip company selection + confirmation)

logic to read company no/jurisdiction from query parameters

---

config/connectors/definitions/webfiling-users.json
config/connectors/mappings/webfiling-users.json
config/managed-objects/alpha-user.json

Update webfiling user defns to include customer ID

---

config/connectors/mappings/webfiling-users.json

Check prior target before setting migrated password status

---

config/am-scripts/scripts-content/ch-update-phone-input-collector.js

Produce different error based on missing field

---

config/am-scripts/scripts-content/ch-join-company-create-relationship.js
config/am-scripts/scripts-content/ch-webfiling-check-for-company-assoc-status.js
config/idm-endpoints/scripts-content/companyauth.js

- added new endpoint action to manage the 'add authorised user' case
- refactored AM script to delegate more to endpoints
- removed return of unnecessary props to UI when user is already authorised

changes to 'add authorised user' logic

---

config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-remove-user-prompt-confirmation.js

- changes to support UI implementation

Remove authz user fixes

---

config/ui/ui-config.json
index.js
scripts/index.js
scripts/update-ui-config.js
tests/scripts/update-ui-config.test.js

Added new UI config command

---

config/am-scripts/scripts-content/ch-callback-update-phone-show-number.js
config/am-scripts/scripts-content/ch-password-reset-text-sent.js
config/am-scripts/scripts-content/ch-registration-verify-token.js

fixed tokenising errors in registration

---

config/am-scripts/scripts-content/ch-fetch-company-info.js
config/internal-roles/IDAM_BUSINESS_SUPPORT.json
config/internal-roles/IDAM_FRONT_END_SUPPORT.json

- modified internal roles as per specs (IDAM-740)
- added 'dormant' as an allowed company status (IDAM-745)

Delegated admin and few more fixes

---

config/services/oauth2-provider.json.tpl

change default webfiling journey to login

chore: change default webfiling journey to login

---

config/idm-endpoints/scripts-content/companyauth.js

important docs update

---

config/am-scripts/scripts-content/ch-join-company-create-relationship.js
config/idm-endpoints/scripts-config.json
config/idm-endpoints/scripts-content/companyauth.js
config/idm-endpoints/scripts-content/removeExpiredInvitations.js
config/idm-endpoints/scripts-content/removeExpiredOnboardedUsers.js

- allow invitations for dormant companies to be sent to users
- improved logging in IDM tasks
- adjusted schedule for relationship removal
- improved logging in scripts

dormant companies fix and more

---

config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-join-company-prompt-for-company-no.js

changes to company association journey to support jurisdiction selection 

changes to company association journey to support jurisdiction selection

---

config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-webfiling-prompt-for-company-no.js

inverted callbacks for EWF company selection
removed comments and debug logging
-->

inverted callbacks for EWF company selection

---

config/am-scripts/scripts-content/ch-callback-show-phone-or-mail.js

- use the new email address in the JSON props for the OTP screen

use the new email address in the JSON props for the OTP screen

---

config/managed-objects/alpha-user.json

Hide legacy password field from REST calls

---

config/am-scripts/scripts-content/oauth2-token-mod.groovy
config/applications/api-filing-client.tpl
config/services/oauth2-provider.json.tpl

- enabled claims_parameter_supported
- added 'company' claim
- added sample OAuth2 application with 'chs' default ACR
- added 'chs' as Oauth2 ACR mapped to CHLogin 

CHS OIDC config

---

config/connectors/definitions/ds-backup.json
config/connectors/mappings/ds-backup.json
config/connectors/mappings/ds-restore.json

chore: update backup for new attributes

---

config/am-scripts/scripts-content/ch-invite-user-send-email.js
config/idm-access-config/idm-access-config.json
config/idm-endpoints/scripts-config.json
config/idm-endpoints/scripts-content/company.js

- fix to invite link generation
- adding a new 'company' endpoint for UI consumption, masking company members personal info
- added IDM access configuration for new endpoint

company endpoint

---

config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-invite-user-create-pending-relationship.js
config/am-scripts/scripts-content/ch-invite-user-email-sent.js
config/am-scripts/scripts-content/ch-invite-user-respond-invite.js
config/am-scripts/scripts-content/ch-join-company-confirmation.js
config/am-scripts/scripts-content/ch-join-company-create-relationship.js
config/am-scripts/scripts-content/ch-join-company-prompt-for-company-authcode.js
config/am-scripts/scripts-content/ch-join-company-wrong-code-error-message.js
config/am-scripts/scripts-content/ch-remove-user-prompt-confirmation.js
config/am-scripts/scripts-content/ch-remove-user-send-email.js
config/am-scripts/scripts-content/ch-send-mfa-email.js
config/am-scripts/scripts-content/ch-send-mfa-sms.js
config/am-scripts/scripts-content/ch-update-email-input-collector.js
config/am-scripts/scripts-content/ch-webfiling-prompt-for-link-confirmation.js
config/idm-endpoints/scripts-content/company.js

removed unnecessary data from callbacks, to remediate issues raised during pen testing

pen test issues fixes

---

config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-invite-user-create-pending-relationship.js
config/am-scripts/scripts-content/ch-remove-user-prompt-confirmation.js
config/am-scripts/scripts-content/ch-update-email-input-collector.js
config/auth-trees/ch-invite-user.json

- masking email addresses in invite/remove user email body
- adding error handing to invite journey
- improved logging
- removed company info from company association callback

masking email addresses in invite/remove user email body

---

config/idm-access-config/idm-access-config.json
config/idm-endpoints/scripts-config.json
config/idm-endpoints/scripts-content/companypag.js

added new endpoint for company pagination/search

added new endpoint for company pagination/search

---

config/am-scripts/scripts-content/ch-join-company-prompt-for-company-authcode.js

reset error message in EWF journey after wrong auth code entered

Bugfix for IDAM-792

---

config/am-scripts/scripts-content/oauth2-token-mod.groovy

fixed case in company claim name

fixed case in company claim name

---

config/auth-trees/ch-webfiling-login.json

Check for resetpwd status during login and send a password reset email.

feat: add resetpwd status flow

---

config/connectors/definitions/webfiling-auth-code.json
config/connectors/definitions/webfiling-auth.json
config/connectors/definitions/webfiling-users.json

chore: update db table connector version

---

config/am-scripts/scripts-content/ch-pwd-input-collector.js

moved company and user info into pageJsonProps

moved company and user info into pageJsonProps

---

config/connectors/mappings/alpha-users-to-webfiling-users.json
config/managed-objects/alpha-user.json

Added correlation query back in &tc

---

config/am-scripts/scripts-content/ch-email-consent-change.js
config/am-scripts/scripts-content/ch-onboarding-verify-token.js
config/am-scripts/scripts-content/ch-registration-error-user-exists.js
config/am-scripts/scripts-content/ch-registration-verify-token.js
config/am-scripts/scripts-content/ch-remove-user-fetch-company-and-user.js
config/am-scripts/scripts-content/ch-remove-user-prompt-confirmation.js

fixed wrong error callbacks structure

fixed wrong error callbacks structure

---

config/am-scripts/scripts-content/ch-invite-user-invalid-email-error-message.js
config/am-scripts/scripts-content/ch-pwd-input-collector.js
config/am-scripts/scripts-content/ch-update-email-input-collector.js
config/am-scripts/scripts-content/ch-update-pwd-check-password-policy.js
config/am-scripts/scripts-content/ch-update-pwd-input-collector.js

Updating callback ID's in errors to match fields.
Defects: IDAM-700, IDAM-782, IDAM-798
- [x ] am-scripts

Update error fields to match callback ID's

---

config/am-scripts/scripts-content/ch-callback-otp-not-valid.js
config/am-scripts/scripts-content/ch-callback-show-phone-or-mail.js
config/am-scripts/scripts-content/ch-callback-update-phone-show-number.js
config/am-scripts/scripts-content/ch-password-reset-text-sent.js
config/am-scripts/scripts-content/ch-password-reset-verify-token.js
config/am-scripts/scripts-content/ch-phone-number-entered.js
config/am-scripts/scripts-content/ch-send-mfa-sms.js
config/am-scripts/scripts-content/ch-webfiling-update-profile.js
config/auth-trees/ch-registration-start.json
config/idm-access-config/idm-access-config.json
config/internal-roles/IDAM_BUSINESS_SUPPORT.json
config/internal-roles/IDAM_FRONT_END_SUPPORT.json

- fixes few UI issues due to missing callbacks
- refactored the INVALID_OTP logic to include the route in the token name
- changed IDs of internal roles, updated IDM access config with new IDs and update/action permissions
- improved Registration tree (and scripts within it) error handling

fixes for IDAM-699, IDAM-800, IDAM-811

---

config/connectors/mappings/webfiling-users.json
config/idm-access-config/idm-access-config.json
config/idm-endpoints/scripts-content/alpha_user_onCreate.js

- added _sortKeys to EWF mapping
- added onCreate as separate script for reference
- removed space from alpha_organization access config

connector changes

---

config/am-scripts/scripts-content/ch-invite-user-respond-invite.js
config/am-scripts/scripts-content/ch-pwd-input-collector.js
config/am-scripts/scripts-content/ch-update-pwd-check-password-policy.js
config/am-scripts/scripts-content/ch-update-pwd-input-collector.js
config/idm-endpoints/scripts-content/companyauth.js

fix to endpoint indexes

---

config/am-scripts/scripts-content/oauth2-token-mod.groovy

Change to correct field name

---

config/connectors/mappings/alpha-users-to-webfiling-users.json

If source (FIDC user) is deleted, also delete EWF user

---

.gitignore
config/agents/ig-agent.json.tpl
helpers/cli-options.js
index.js
scripts/index.js
scripts/update-agents.js
tests/scripts/update-agents.test.js

Add a script to create and IG agent in FIDC

feat: add ig agent script

---

config/am-scripts/scripts-content/ch-password-reset-pwd-updated.js
config/am-scripts/scripts-content/ch-update-pwd-load-new-pwd-for-patch.js

- removed onboarding date when pwd is reset/changed
- fomatting/error handling

removed onboarding date when pwd is reset/changed

---

config/connectors/mappings/webfiling-users.json
config/idm-endpoints/scripts-config.json
config/idm-endpoints/scripts-content/scrs-wrapper.js
config/idm-endpoints/scripts-content/scrs.js
scripts/update-idm-endpoints.js

- added logic to create schedules in IDM
- added a SCRS wrapper script which invokes the IDM SCRS endpoint
- amended IDM endpoint to support invocation from wrapper script
- removed setting of onboarding date on SCRS script

SCRS fixes

---

.gitignore
config/idm-endpoints/scripts-content/company.js

Ensure that the search for company name and number is case-insensitive.

Case Insensitive search for Company Name/Number from UI when search for Company Details

---

scripts/get-auth-tree.js

Fix an issue with missing nodes
- [X ] auth-trees

Fix to include Journey sub-node content that was missing on export using get-auth-tree command

---

config/managed-objects/event-scripts/alpha_user_onCreate.js
config/managed-objects/event-scripts/alpha_user_onUpdate.js
scripts/update-managed-objects.js

Update of managed objects now also updates/includes the lifecycle event scripts, if found to exist in the configuration folder under managed-objects for each managed object within the realm.
- [ X] managed-objects

Modify managed objects update to also include event lifecycle scripts

---

config/connectors/mappings/event-scripts/alphaUser_webfilingUser_onError.js
config/connectors/mappings/event-scripts/chsUsers_alphaUser_onCreate.js
config/connectors/mappings/event-scripts/chsUsers_alphaUser_onUpdate.js
config/connectors/mappings/event-scripts/webfilingUser_alphaUser_onCreate.js
config/connectors/mappings/event-scripts/webfilingUser_alphaUser_onError.js
config/connectors/mappings/event-scripts/webfilingUser_alphaUser_onUpdate.js
scripts/update-connector-mappings.js

Add externalised event lifecycle scripts for connector mappings.

Added additional event scripts for connector mappings

---

config/connectors/mappings/alpha-users-to-webfiling-users.json
config/connectors/mappings/mongodb-users.json
config/connectors/mappings/webfiling-users.json
config/managed-objects/alpha-role.json
config/managed-objects/alpha-user.json
config/managed-objects/bravo-role.json
config/managed-objects/bravo-user.json

Removed the script content from the main object JSON where there is now support to hold them as an externalised file. This is so as to remove ambiguity as to where they should be modified within the config project.

Removed event scripts from main object JSON where they are now externalised

---

config/idm-endpoints/scripts-config.json
scripts/update-idm-endpoints.js

fixed schedule ID format, removed unused properties, updated PR template

fixed script ID format, removed unused properties

---

config/am-scripts/scripts-config.json
config/am-scripts/scripts-content/ch-registration-confirmation-email-sent.js
config/am-scripts/scripts-content/ch-registration-resend-email-confirm.js
config/auth-trees/ch-registration-start.json
config/auth-trees/ch-registration-verify.json

added extra node/script to show resend/change address screen after registration email is sent

changes to registration journey 

---

tests/scripts/update-connector-mappings.test.js

Updated unit tests for connector mappings

Updated unit tests for connector mappings

---

config/am-scripts/scripts-library/ch-library-functions.js

Support for modifying the log level for _log() operations

Support for modifying the log level for _log() operations

---

config/am-scripts/scripts-library/ch-library-functions.js

Helper function in the AM script library to get Journey Name.

Support for getting the current journey name from requestParameters

---

config/am-scripts/scripts-library/ch-library-functions.js

* Padding function for non-obfuscated phone number
* Rework of phone obfuscation to use same padding function
* Standard JS formatting

Padding function for non-obfuscated phone number

---

config/am-scripts/scripts-content/ch-callback-to-capture-otp-response.js

Remove option from callback on OTP resend page that isn't relevant.

Remove invalid choice from Email resend page

---

config/connectors/definitions/webfiling-users.json

pointing EWF USERS connector to the new AWS KERMIT DB

---

config/idm-endpoints/scripts-content/scrs.js
helpers/file-filter.js
index.js
scripts/update-idm-endpoints.js
tests/helpers/file-filter.test.js

* Check that onboarding date is not set for new users
* Ensure that new users are created with inactive status
* Modification to update-fidc utility to support `--ff` option for IDM Endpoints

SCRS user is inactive, also support FilenameFilter for IDM-endpoints

---

config/am-scripts/scripts-content/ch-create-notify-jwt.js
config/am-scripts/scripts-content/ch-load-jwt-keys.js
config/am-scripts/scripts-content/ch-scrs-send-email.js
config/am-scripts/scripts-content/ch-scrs-validate-params.js

* Check the status of the SCRS user, and send a different email based on whether the user was newly created or pre-existing.

Send a different email based on whether the SCRS user is new or existing

---

config/am-scripts/scripts-content/ch-choose-otp-method.js
config/am-scripts/scripts-content/ch-mfa-sub-flow-setup.js
config/am-scripts/scripts-content/ch-resend-otp-via-mfa-route.js
config/am-scripts/scripts-content/ch-send-mfa-sms.js
config/am-scripts/scripts-content/ch-update-phone-input-collector.js

* Issue was found in testing where a flag relating to changed phone number was being passed down in TransientState which was then not available in the Inner Tree required to send the SMS

Fix issue with Transient State variable not available in Inner Tree

---

config/am-scripts/scripts-content/ch-scrs-send-email.js

* Updated to include Email address in SCRS new user email.

Updated to include subject name in SCRS new user email

---

config/am-scripts/scripts-content/ch-invite-user-respond-invite.js
config/am-scripts/scripts-content/ch-notify-authorized-users.js
config/connectors/definitions/webfiling-users.json

- logic to skip notification for user who accepts the invite
- applied formatting rules to the 2 scripts

logic to skip notification for user who accepts the invite

---

config/am-scripts/scripts-content/ch-invite-user-fetch-company.js
config/am-scripts/scripts-content/ch-invite-user-send-email-confirm.js

* Add Company Name to callback using companyData held in shared state

Add Company Name to Invite User via Email callback

---

scripts/update-managed-objects.js

* As part of merging scripts ensure that a managed object type is present

Add type to manage object if missing

---

package-lock.json

* Requires package-lock.json to be added to SCCS 

Added package-lock.json to source control

---

config/am-scripts/scripts-content/ch-callback-to-capture-otp-response.js

Add additional flags to pagePropsJSON to allow UI to indicate to the user whether the OTP has been resent, or the OTP entered was incorrect

idam-990/Add pagePropsJSON flags for RESEND and INCORRECT OTP scenarios

---

config/am-scripts/scripts-content/ch-invite-user-send-email.js
config/am-scripts/scripts-content/ch-load-jwt-keys.js
config/am-scripts/scripts-content/ch-onboarding-verify-token.js
config/am-scripts/scripts-content/ch-password-reset-send-email.js
config/am-scripts/scripts-content/ch-password-reset-verify-token.js
config/am-scripts/scripts-content/ch-registration-verify-token.js

Fix equality check changes from earlier logging update commit that seems to have broken based on differences on equality checks

idam-1022/Fix bug with equality check that broke apps

---

config/idm-endpoints/scripts-content/scrs.js

* Retrieve the PARENT_USERNAME from EWF to use in frIndexedString1 as part of FIDC user create
* Cached response (if available) to improve performance during batch of companies being processed

idam-784/get parent username from EWF to use on FIDC user create

---

config/am-scripts/scripts-content/ch-send-mfa-sms.js
config/am-scripts/scripts-content/ch-webfiling-update-profile.js
config/auth-trees/ch-webfiling-complete-profile.json

* Modified Onboarding journey to pass flag to SMS script to handle specific onboarding case
* Handle HTTP response code from Notify signalling error (such as invalid phone, Notify down)
* Add error status to pagePropsJSON for UI to show error message

idam-1023/Catch invalid phone number or Notify service issue and return error codes

---

config/connectors/mappings/properties-transform-scripts/webfilingAuthCode_alphaOrg/authCodeIsActive.js
config/connectors/mappings/webfilingAuthCode_alphaOrg.json
scripts/update-connector-mappings.js

* Support the merging of Connector property transform scripts from external files

idam-1027/property transform source

---

config/auth-trees/ch-registration-verify.json

* Additional check of username prior to create, and after various UI pages asking for password and consent to reduce the risk of name clash in CHVerifyReg

idam-1024/Additional check for same username prior to create of user

---

config/am-scripts/scripts-library/ch-library-functions.js

* Add a SpanID to each log call that is consistent across the entire journey allowing tracing of session calls across all scripts in the same journey

idam-999/Add a span ID to each log call consistent across the AM journey

---

helpers/file-filter.js
scripts/update-scripts.js

* Basic linting framework for AM scripts
* Warning generated if "let" keyword used in AM scripting

idam-999/Added basic linting support for AM Scripts

---

scripts/update-idm-endpoints.js

** Added a check for end of line comments that cause scripts to fail

idam-999/Added basic linting support for IDM scripts

---

config/am-scripts/scripts-config.json
config/am-scripts/scripts-content/ch-onboarding-verify-token.js
config/am-scripts/scripts-content/ch-scrs-activation-check-params.js
config/am-scripts/scripts-content/ch-scrs-send-email.js
config/am-scripts/scripts-content/ch-scrs-unlock-user.js
config/am-scripts/scripts-library/ch-library-functions.js
config/auth-trees/ch-scrs-activation.json

- added scripts and tree for SCRS activation journey

activation journey

---

config/idm-endpoints/scripts-content/scrs.js

* Use Harmonia supplied Bearer Tokens for Dev
* Rename constants to be uppercase

idam-784/add harmonia bearer tokens

---

scripts/update-scripts.js

idam-1034/fix linter

---

config/connectors/definitions/webfiling-users.json
config/connectors/mappings/webfilingUser_alphaUser.json

Fixes to mapping and connector

fixed to mapping

---

config/am-scripts/scripts-content/ch-pwd-input-collector.js

added missing stage name for pwd collector in activation journey

added missing stage name for pwd collector in activation journey

---

config/connectors/mappings/alphaUser_webfilingUser.json

* Swap behaviour to CREATE for MISSING scenario, rather than EXCEPTION

idam-1048/swap behaviour to CREATE for MISSING scenario

---

config/idm-endpoints/scripts-content/scrs.js

* Ensure that the linkTokenId is consistent across emails, and runs of the scheduler

idam-784/fix tokenid assign to user to ensure re-use if existing

---

config/am-scripts/scripts-content/ch-scrs-send-email.js

add 'type' param to tell UI which notification to show
- [xthatt's the issue, th] scripts (AM)

add 'type' param to tell UI which notification to show

---

config/am-scripts/scripts-content/ch-scrs-send-email.js

Extra param scrs link

---

config/am-scripts/scripts-content/ch-scrs-validate-params.js

* fix check for new user flag for SCRS email link

idam-1049/fix check for new user flag for SCRS email link

---

config/am-scripts/scripts-content/ch-scrs-send-email.js

* Ensure correct email is sent for user type

idam-1049/fix email type sent

---

config/am-scripts/scripts-content/ch-scrs-send-email.js

* fix email query params encoding of & between params

idam-1049/fix email query params encoding

---

config/connectors/mappings/alphaUser_webfilingUser.json
config/connectors/mappings/cleanup_FIDC_companies.json
config/connectors/mappings/cleanup_FIDC_users.json

changes to make cleanup more effective

Cleanup mappings

---

config/password-policy/password-policy.json

* Make config policy match the same policy on Dev

idam-1037/set standard password policy

---

config/am-scripts/scripts-config.json
config/am-scripts/scripts-content/ch-check-otp-resend-address.js
config/auth-trees/ch-multi-factor-generic.json
scripts/update-scripts.js

* Added support for intermediate page after resend selected
* For now, the AM script code is commented out as it breaks the UI (need Paul to add a new Stage into the UI)

idam-1072/add check email/mobile number page after resend selected

---

config/connectors/mappings/cleanup_FIDC_users.json

increased source page size for users cleanup mapping

increased source page size for users cleanup mapping

---

config/connectors/mappings/cleanup_FIDC_companies.json
config/connectors/mappings/cleanup_FIDC_users.json

Cleanup mapping page size

---

config/connectors/mappings/chsMongoCompanyProfile_alphaOrg.json
config/connectors/mappings/event-scripts/alphaUser_webfilingUser_onError.js
config/connectors/mappings/event-scripts/chsMongoCompanyProfile_alphaOrg_onError.js
config/connectors/mappings/event-scripts/webfilingAuthCode_alphaOrg_onError.js
config/connectors/mappings/event-scripts/webfilingUser_alphaUser_onError.js
config/connectors/mappings/properties-transform-scripts/webfilingAuthCode_alphaOrg/authCodeIsActive.js
config/connectors/mappings/webfilingAuthCode_alphaOrg.json

improvement to logging, removed verbose logging of auth code transformation

logging changes

---

config/am-scripts/scripts-library/ch-config-functions.js
config/am-scripts/scripts-library/ch-library-functions.js
config/idm-endpoints/scripts-content/scrs.js
config/variables-secrets/secrets.json
config/variables-secrets/variables.json
helpers/fidc-get.js
helpers/fidc-post.js
helpers/fidc-request.js
index.js
scripts/index.js
scripts/restart-fidc.js
scripts/update-scripts.js
scripts/update-secrets.js
scripts/update-variables.js

* Support for creating/updating variables using ESV API
* Support for creating/updating secrets using ESV API
* Merging of Variables and Secret values from the environment
* Support for triggering a reboot of FIDC services
* AM Script library functions for retrieving Variable or Secret values in a safe way

idam-1040/FIDC management of variables, secrets and restarts

---

config/am-scripts/scripts-content/ch-get-idm-access-token.js
config/variables-secrets/secrets.json
helpers/cli-options.js

* Remove explicit password and username from script
* Add FIDC secret for username

idam-1040/Remove tree service username and password, extracted to secrets in FIDC

---

config/am-scripts/scripts-content/ch-get-idm-access-token.js

* Use variable call, not secret call in JS script

idam-1040/Use correct function call

---

helpers/fidc-get.js
helpers/fidc-post.js
helpers/fidc-request.js
scripts/update-secrets.js
scripts/update-variables.js

* Check for current values of secrets and variables before forcing an update
* Signal via stdout whether a restart of FIDC services is required

idam-1040/Check for current values before updating

---

helpers/cli-options.js
index.js
scripts/get-esv-concourse.js
scripts/index.js

* Dump ESV values in Concourse Pipeline mode (with regionName value)
* Dump ESV values for passing to DevOps for inclusion in SSM
* (Optional) Dump decoded ESV values for local inspection 

idam-1040/Dump secrets and variables in Concourse format

---

config/idm-endpoints/scripts-config.json
config/idm-endpoints/scripts-content/scrs-wrapper.js

* Modify SCRS schedule to be 30 mins (from 60 mins)
* Modify page size iterations to account for 2000 incorporations over a business day (10 hours)

idam-842/configure SCRS schedule and page sizes

---

config/am-scripts/scripts-content/ch-check-for-session.js
config/am-scripts/scripts-content/ch-onboarding-verify-token.js
config/am-scripts/scripts-content/ch-scrs-activation-check-params.js
config/am-scripts/scripts-content/ch-webfiling-check-for-session.js
config/am-scripts/scripts-content/ch-webfiling-prompt-for-company-no.js
config/am-scripts/scripts-content/ch-webfiling-store-authcode-in-session.js
config/am-scripts/scripts-content/ch-webfiling-store-pwd-in-session.js
config/am-scripts/scripts-library/ch-library-functions.js

* Centralise the check for whether a user is authenticated

idam-1071/check if user is logged in

---

config/am-scripts/scripts-content/ch-check-otp-resend-address.js

* Modify the stage name
* Add support for onboarding (getting the email/phone number from sharedState)
* Fix missing variable

idam-1073/resend confirmation page

---

config/am-scripts/scripts-content/ch-check-otp-resend-address.js
scripts/update-connector-definitions.js

* Comment out check of OTP resend again

idam-1082/comment out AM script again

---

config/am-scripts/scripts-content/ch-remove-user-fetch-company-and-user.js
config/idm-endpoints/scripts-content/companyauth.js

* Modify IDM endpoint to still return (optionally) if company has no auth code or isn't active or dormant
* Modify Journey AM script to pass optional parameter to make company checks more lenient 

idam-1087/allow removal of company if no auth code

---

config/am-scripts/scripts-content/ch-invite-user-prompt-for-email.js
config/am-scripts/scripts-content/ch-login-input-check.js
config/am-scripts/scripts-content/ch-update-email-input-collector.js
config/am-scripts/scripts-content/ch-update-phone-input-collector.js
config/am-scripts/scripts-content/ch-webfiling-update-profile.js
config/am-scripts/scripts-library/ch-library-functions.js

* Centralise valid phone & email functions
* Replace usages of checking phone and email to use library functions

idam-1040/script tidy up

---

config/am-scripts/scripts-content/ch-mfa-sub-flow-setup.js

* Fix bug evident in UI where the OTP Setup script for SCRS Journey was not setting the OTP stage name correctly

idam-1090/scrs-otp-bug

---

config/am-scripts/scripts-content/ch-scrs-activation-check-params.js

* Fix missing company name (shown as undefined) on SCRS password entry screen

idam-1090/scrs company name missing on password screen

---

.gitignore
helpers/restart-fidc-file-helper.js
scripts/update-secrets.js
scripts/update-variables.js

* Create file FIDC_RESTART_REQUIRED.txt is a FIDC restart is required after updating secrets or variables

idam-1040/create fidc restart marker file

---

bash-scripts/restart_fidc_if_required.sh

* CI script to support the restart of FIDC server based on a marker file

idam-1040/update fidc bash script for CI build

---

helpers/restart-fidc-file-helper.js

* Fix linting to make unit tests run OK again

idam-1040/fix standard linting

---

config/connectors/mappings/alphaUser_webfilingUser.json
config/connectors/mappings/chsMongoCompanyProfile_alphaOrg.json
config/connectors/mappings/cleanup_FIDC_companies.json
config/connectors/mappings/cleanup_FIDC_users.json
config/connectors/mappings/event-scripts/alphaUser_webfilingUser_onError.js
config/connectors/mappings/event-scripts/alphaUser_webfilingUser_onUpdate.js
config/connectors/mappings/event-scripts/chsMongoCompanyProfile_alphaOrg_onError.js
config/connectors/mappings/event-scripts/webfilingAuthCode_alphaOrg_onError.js
config/connectors/mappings/event-scripts/webfilingUser_alphaUser_onError.js
config/connectors/mappings/webfilingAuthCode_alphaOrg.json
config/connectors/mappings/webfilingUser_alphaUser.json
config/connectors/schedules/ds-backup.json

- remove the cleanup mappings
- disable the ds-backup scheduled recon (to avoid interference with other mappings)
- re-enable the MISSING behavior to DELETE on the outbound user sync mapping
- removed the _queryFilter from the mappings source queries

several mapping fixes

---

config/connectors/definitions/ds-backup.json

* Update DS Backup connector version

idam-1040/fix DS Connector version

---

.gitignore

* Support for local .env files per region (.gitignore changed only)

idam-1040/support for regional env files

---

bash-scripts/get_idm_access_token.sh

* Fix FIDC cookie name for Staging

idam-1040/fix cookie name for Staging

---

config/managed-users/tree-service-user.json.tpl
scripts/update-managed-users.js

* fix managed users env variable name

idam-1040/fix managed users env variable name

---

config/am-scripts/scripts-content/ch-check-otp-resend-address.js

* Intermediate page for OTP resend to check details

idam-1073/Intermediate page for OTP resend to check details

---

config/am-scripts/scripts-content/ch-check-otp-resend-address.js

* Ensure that the phone and email details are obfuscated

idam-1116/Obfuscate email and phonenumber on OTP resend check page

---

config/am-scripts/scripts-content/ch-password-reset-send-email.js
config/am-scripts/scripts-content/ch-registration-send-email.js

* Remove /am/XUI links that bleed AM journey information into the public domain

Idam 1033/remove am xui links

---

config/idm-endpoints/scripts-content/scrs.js

* Set SCRS company status as active, if created

idam-1120/scrs-company-set-to-active

---

config/am-scripts/scripts-content/ch-invite-user-fetch-company.js

* Fix invalid JS call causing AM script to error

idam-1104/Fix invalid JS call

---

config/am-scripts/scripts-content/ch-invite-user-send-email.js
config/am-scripts/scripts-content/ch-mfa-sub-flow-setup.js

* Fix email link token for invite resend
* Fix MFA route for onboarding flow in generic OTP subflow

idam-949/Fix email link token for invite resend

---

config/am-scripts/scripts-content/ch-webfiling-update-profile.js

* Incorrect tokenID passed to UI when phone is invalid

idam-1063/Incorrect tokenID passed to UI when phone is invalid

---

config/am-scripts/scripts-content/ch-invite-user-send-email.js
config/am-scripts/scripts-content/ch-notify-authorized-users.js
config/am-scripts/scripts-content/ch-remove-user-send-email.js
config/am-scripts/scripts-content/ch-scrs-send-email.js

removed CY language support from some journeys

---

config/am-scripts/scripts-content/ch-send-mfa-email.js
config/am-scripts/scripts-content/ch-send-mfa-sms.js

* Fix Stage Name for OTP issues
* 

idam-1128/Fix Stage Name for OTP issues

---

config/am-scripts/scripts-content/ch-create-notify-jwt.js
config/variables-secrets/secrets.json

* Remove Gov Notify API key from variable and make it a secret

idam-1108/Disentangle Gov Notify API key

---

config/idm-endpoints/scripts-content/scrs.js

* Added query for CHS Company & Auth Code to get company details for a better company creation model

Idam 1127/scrs company create

---

config/am-scripts/scripts-config.json
config/am-scripts/scripts-content/ch-registration-initial-capture-check.js
config/am-scripts/scripts-content/ch-registration-initial-capture.js
config/auth-trees/ch-registration-start.json

* Remove Registration Page Node & Attribute Collector
* Replaced with Scripted Node & Validator Script

Idam 1128/replace registration page node capture of email and mobile number

---

config/idm-endpoints/scripts-content/scrs.js

* if/else part was not required for create company if auth code was not present in Oracle

idam-1117/Fix missing Auth Code path after testing

---

config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-invite-user-prepare-user-onboarding.js
config/am-scripts/scripts-content/ch-join-company-create-relationship.js
config/am-scripts/scripts-content/ch-onboarding-verify-token.js
config/am-scripts/scripts-content/ch-require-mfa-check.js
config/am-scripts/scripts-content/ch-update-last-login.js
config/am-scripts/scripts-library/ch-library-functions.js
config/connectors/mappings/webfilingAuthCode_alphaOrg.json
config/connectors/mappings/webfilingUser_alphaUser.json
config/managed-objects/alpha-organization.json

- removed sourceQuery from EWF>FIDC user mapping
- removed mapping transf.script to set auth code active flag
- removed isAuthCodeActive from alpha_organization and auth code mapping
- added company/auth code lookup from connectors in company assoc/EWF journeys
- added logic to check the auth code expiry date

company lookup changes

---

config/am-scripts/scripts-content/ch-password-reset-confirmation-email-sent.js
config/am-scripts/scripts-content/ch-password-reset-send-email.js
config/auth-trees/ch-password-reset.json

* Support for resending the reset password link, or starting anew

idam-1146/Reset Password resend or restart

---

config/am-scripts/scripts-config.json
config/am-scripts/scripts-content/ch-check-user-source.js
config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-fetch-hashed-password.js
config/am-scripts/scripts-library/ch-library-functions.js
config/auth-trees/ch-login.json
config/auth-trees/ch-webfiling-login.json
config/managed-objects/alpha-user.json

- added new script for on-demand user creation/update
- updated CHLogin and CHWebFiling-Login journeys to include the above
- made legacyPassword field visible in alpha_user
- fixed bug in on-demand company update

added on-demand user creation/update in login journeys

---

config/internal-roles/IDAM_BUSINESS_SUPPORT.json
config/internal-roles/IDAM_FRONT_END_SUPPORT.json
scripts/update-internal-roles.js

* Fix roles that had a field that is now removed

idam-1114/increase-complexity-change-gov-uk-fix-roles

---

config/idm-endpoints/scripts-content/companyauth.js
config/idm-endpoints/scripts-content/scrs.js
config/internal-roles/IDAM_BUSINESS_SUPPORT.json
config/internal-roles/IDAM_FRONT_END_SUPPORT.json

removing references of isAuthCodeActive company flag

removing references of isAuthCodeActive company flag

---

config/auth-trees/ch-scrs-activation.json

* Recreate project version of Auth Tree using version from server

idam-1193/Fix CHSCRSActivation auth tree to save using update-fidc

---

config/am-scripts/scripts-content/ch-check-user-source.js

- logging improvement
- additional check for PARENT_USERNAME discrepancies of existing users

additional check for PARENT_USERNAME discrepancies of existing users

---

index.js

fix linting

---

config/am-scripts/scripts-content/ch-fetch-company-info.js

* Use the correct token to return an error when invalid company number or auth code

idam-908/Use correct token for File Company UI error message

---

config/am-scripts/scripts-content/ch-pwd-input-collector.js
config/am-scripts/scripts-content/ch-update-pwd-input-collector.js

* Modify handling of various issues related to entering passwords for Create/Update password

idam-905/Pass back tokens for various password UI issues

---

config/auth-trees/ch-update-email.json
config/auth-trees/ch-update-legacy-password.json
config/auth-trees/ch-update-password.json
config/auth-trees/ch-update-phone-number.json

* Update/Remove retry limits in Auth Trees

idam-1214/Update or remove retry limits in auth trees

---

bash-scripts/get_idm_access_token.sh

* Get IDM access token support for live

idam-1264/Get IDM access token support for live

---

.github/pull_request_template.md

* Updated the commit message to add new elements, and a reminder about `standard`

idam-1264/Update commit message

---

config/idm-endpoints/scripts-content/scrs.js

* Better handling of HTTP 400 responses for Emails associated with a company incorporation in SCRS

idam-1100/Handle HTTP 400 errors better in SCRS email processing

---

config/idm-endpoints/scripts-content/company.js

- optimised IDM query to fetch user companies in 1 query instead of N
- added logic to query EWF/CHS connectors to fetch updated data

changed IDM endpoint to trigger a company data refresh

---

config/am-scripts/scripts-library/ch-library-functions.js

* Better handling (removed regex)

idam-1205/Better handling for Phone No format

---

config/managed-objects/event-scripts/alpha_user_onCreate.js
config/managed-objects/event-scripts/alpha_user_onUpdate.js
config/variables-secrets/secrets.json
config/variables-secrets/variables.json

- added hash gen API url and key to ESVs
- changed onCreate/onUpdate scripts to use the ESVs
- improved logging

changes to enable usage of API for hash generation

---

scripts/update-auth-trees.js

* Import auth-tree nodes and tree definitions synchronously

idam-1279/Upload auth trees synchronously

---

config/connectors/schedules/auth-codes.json
config/connectors/schedules/companies.json
config/connectors/schedules/users.json

adding recons schedules

---

config/password-policy/password-policy.json

* Password policy changes to remove upper, lower, digit, symbols

idam-1262/Password policy changes to remove upper, lower, digit, symbols

---

config/connectors/schedules/users.json

slight adjustment of user recon schedule

---

config/auth-trees/ch-multi-factor-generic.json

* Sign out if you fail OTP too many times

idam-1288/Sign out if you fail OTP too many times

---

config/am-scripts/scripts-content/ch-update-pwd-check-password-policy.js
config/am-scripts/scripts-library/ch-library-functions.js

* Password policy changes to fix partial use of user attribute

Idam 1262/password policy changes

---

config/am-scripts/scripts-library/ch-library-functions.js

* Obfuscate if not logged in, based on FR session status

Idam 1071/obfuscate if not logged in

---

config/am-scripts/scripts-content/ch-mfa-sub-flow-setup.js
config/am-scripts/scripts-content/ch-send-mfa-email.js
config/am-scripts/scripts-content/ch-send-mfa-sms.js
config/am-scripts/scripts-content/ch-update-phone-input-collector.js

* Modify stagename to GENERIC_ERROR if OTP send fails

idam-1295/Modify stagename to GENERIC_ERROR if OTP send fails

---

config/idm-endpoints/scripts-content/company.js
config/variables-secrets/variables.json

- adding null/empty checks in company IDM script
- adding recon schedule/enabled flags variables

new vars and null checks

---

config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-webfiling-check-for-company-assoc-status.js

* Additional Logging for Company Association, and NPE checks

idam-1304/Additional Logging for Company Association, and NPE checks

---

config/am-scripts/scripts-content/ch-callback-to-capture-otp-response.js
config/am-scripts/scripts-content/ch-update-phone-input-collector.js

* Previous phone number shown on UI when changing phone number

idam-1205/Previous phone number shown on UI when changing phone number

---

config/am-scripts/scripts-content/ch-fetch-company-info.js

fix for fetch company data logic 

---

config/am-scripts/scripts-library/ch-library-functions.js

* Phone number formatting for usability

idam-1310/Phone number formatting

---

config/am-scripts/scripts-content/ch-fetch-company-info.js

adding check for connector REST call status code

---

config/am-scripts/scripts-content/oidc-claims-script.groovy
config/services/oauth2-provider.json.tpl

Fix error on filing for new user
* Addition of a new ACR value for OAuth2 service
* Logging statements in OIDC claims script

idam-1316/Fix error on filing for new user

---

scripts/update-secrets.js
scripts/update-variables.js

* Kill with exit code 1 if update-fidc if missing ESV

idam-1318/Kill update-fidc if missing ESV

---

config/am-scripts/scripts-content/ch-login-input-check.js

* Invalid sign in details against login page
* Use seperate tokens for each field

idam-1272/Invalid sign in details against login page

---

config/am-scripts/scripts-config.json
config/am-scripts/scripts-content/ch-update-email-confirmation.js
config/auth-trees/ch-update-email.json

* Goto signed out page after changing email or password, with message banner

idam-1321/Show sign out page after changing email or password

---

index.js
scripts/index.js
scripts/update-esv-and-restart.js

idam-1332/Updated ESVs in one go

---

config/am-scripts/scripts-content/ch-update-pwd-load-new-pwd-for-patch.js
config/am-scripts/scripts-content/ch-validate-authcode.js
config/connectors/definitions/ds-backup.json
config/connectors/definitions/mongodb-roles.json
config/connectors/definitions/mongodb-users.json

- disabled unused connectors
- removed sensitive log statements from AM scripts 

Remove sensitive log statements

---

config/am-scripts/scripts-content/ch-callback-to-capture-otp-response.js
config/am-scripts/scripts-content/ch-check-for-session.js
config/am-scripts/scripts-content/ch-invite-user-send-email.js
config/am-scripts/scripts-content/ch-join-company-confirmation.js
config/am-scripts/scripts-content/ch-notify-authorized-users.js
config/am-scripts/scripts-content/ch-registration-send-email.js
config/am-scripts/scripts-content/ch-remove-user-send-email.js
config/am-scripts/scripts-content/ch-scrs-send-email.js
config/am-scripts/scripts-content/ch-send-mfa-email.js
config/am-scripts/scripts-content/ch-send-mfa-sms.js
config/am-scripts/scripts-content/ch-update-pwd-check-password-policy.js
config/am-scripts/scripts-content/ch-validate-authcode.js
config/am-scripts/scripts-content/ch-webfiling-check-for-session.js
config/am-scripts/scripts-content/ch-webfiling-prompt-for-company-no.js
config/am-scripts/scripts-content/ch-webfiling-store-authcode-in-session.js
config/am-scripts/scripts-content/ch-webfiling-store-pwd-in-session.js

… Passwords
Remove sensitive log information such as OTP, Auth Codes and passwords

idam-824/Remove sensitive log information such as OTP, Auth Codes and passwords

---

config/am-scripts/scripts-content/ch-check-password-status.js
config/am-scripts/scripts-content/ch-check-user-source.js
config/am-scripts/scripts-content/ch-login-input-check.js
config/am-scripts/scripts-content/ch-login-soft-lock-increment-counter.js

* Fix login issue being bound to wrong user

idam-1342/Fix login issue being bound to wrong user

---

config/am-scripts/scripts-content/ch-scrs-send-email.js

Fix SCRS user type query param

idam-1348/Fix SCRS user type query param

---

config/am-scripts/scripts-content/ch-callback-prompt-for-company-info.js
config/am-scripts/scripts-content/ch-callback-prompt-for-validate-credential.js
config/am-scripts/scripts-content/ch-validate-credential.js

idam-1348/Coerce user lambda response

---

config/am-scripts/scripts-content/ch-update-phone-input-collector.js
config/auth-trees/ch-update-phone-number.json

allow to specify an empty phone number in the 'change phone number' journey

allow empty number to be set

---

config/services/oauth2-provider.json.tpl

Update attributes that have been renamed by Forgerock

Update attributes that Forgerock renamed

---

config/services/oauth2-provider.json.tpl

Further attribute updates

---

config/idm-endpoints/scripts-config.json
config/variables-secrets/variables.json
scripts/update-idm-endpoints.js

adding vars for the 3 schedules and adding ESVs to config

---

config/idm-endpoints/scripts-content/scrs.js

Added  logging for when company filers are not found to scrs.js script

logging enhancement for when company filers are not found

---

README.md

added info about promotions

---

config/am-scripts/scripts-content/ch-validate-authcode.js

- made the auth code check case insensitive

made the auth code check case insensitive

---

config/am-scripts/scripts-content/ch-callback-general-error.js
config/am-scripts/scripts-content/ch-check-user-source.js
config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-invite-user-create-pending-relationship.js
config/am-scripts/scripts-content/ch-invite-user-fetch-company.js
config/am-scripts/scripts-content/ch-invite-user-respond-invite.js
config/am-scripts/scripts-content/ch-join-company-create-relationship.js
config/am-scripts/scripts-content/ch-notify-authorized-users.js
config/am-scripts/scripts-content/ch-onboarding-verify-token.js
config/am-scripts/scripts-content/ch-password-reset-send-email.js
config/am-scripts/scripts-content/ch-registration-send-email.js
config/am-scripts/scripts-content/ch-remove-user-fetch-company-and-user.js
config/am-scripts/scripts-content/ch-remove-user-prompt-confirmation.js
config/am-scripts/scripts-content/ch-send-mfa-sms.js
config/am-scripts/scripts-content/ch-update-legacy-password.js
config/am-scripts/scripts-content/ch-update-pwd-check-password-policy.js
config/am-scripts/scripts-content/ch-webfiling-check-for-company-assoc-status.js
config/am-scripts/scripts-library/ch-library-functions.js
config/idm-endpoints/scripts-content/companyauth.js
config/internal-roles/IDAM_BUSINESS_SUPPORT.json
config/internal-roles/IDAM_FRONT_END_SUPPORT.json

- improving logging everywhere
- fix for company status check (allowing all companies which are not 'dissolved')
- fixed internal roles filters according to the new status check

logging and company status check

---

config/am-scripts/scripts-content/ch-callback-login-error.js
config/am-scripts/scripts-content/ch-check-user-source.js
config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-get-idm-access-token.js
config/am-scripts/scripts-content/ch-login-input-check.js
config/am-scripts/scripts-content/ch-login-soft-lock-increment-counter.js
config/am-scripts/scripts-content/ch-webfiling-prompt-for-company-no.js
config/am-scripts/scripts-library/ch-library-functions.js
config/idm-endpoints/scripts-content/company.js
config/idm-endpoints/scripts-content/companyauth.js

- encode/trim company number to avoid exceptions
- added more logging in AM and IDM
- added UTC timestamp in IDM logging

Encode company no and more logging

---

config/am-scripts/scripts-content/ch-check-user-source.js
config/am-scripts/scripts-content/ch-join-company-create-relationship.js
config/am-scripts/scripts-content/ch-remove-user-prompt-confirmation.js

- fixing encoding for user on demand sync
- improved logging for add/remove company -

logging and encoding fixes

---

config/am-scripts/scripts-content/ch-check-user-source.js
config/am-scripts/scripts-content/ch-fetch-company-info.js
config/am-scripts/scripts-content/ch-get-idm-access-token.js
config/am-scripts/scripts-content/ch-join-company-create-relationship.js
config/am-scripts/scripts-content/ch-login-soft-lock-check.js
config/am-scripts/scripts-content/ch-login-soft-lock-increment-counter.js
config/am-scripts/scripts-content/ch-login-soft-lock-reset-counter.js
config/am-scripts/scripts-content/ch-notify-authorized-users.js
config/am-scripts/scripts-content/ch-update-last-login.js
config/am-scripts/scripts-content/ch-update-pwd-check-password-policy.js
config/am-scripts/scripts-content/ch-webfiling-check-for-company-assoc-status.js
config/idm-endpoints/scripts-content/company.js

New logging

---

config/auth-trees/settings/tree-auth.json
config/connectors/mappings/chsMongoCompanyProfile_alphaOrg.json

- increased duration of auth trees session
- disable clustered recon for companies (following support ticket)

Increase auth tree timeout

---

config/am-scripts/scripts-content/ch-check-password-status.js
config/am-scripts/scripts-content/ch-webfiling-prompt-for-company-no.js
config/am-scripts/scripts-content/ch-webfiling-store-pwd-in-session.js
config/auth-trees/ch-webfiling.json
config/connectors/mappings/chsMongoCompanyProfile_alphaOrg.json

- restored clustered recon for companies
- logging improvements
- added extra final step to CHWebFiling journey to put the pwd in session again
- commented out the removal of the pwd from sharedState
- restoring the pwd in sharedState from session

Session password fix/logging/clustered recon

---

config/idm-endpoints/scripts-content/company.js
config/idm-endpoints/scripts-content/companyauth.js

added null checks before accessing _refProperties

added null checks before accessing _refProperties

---

config/managed-objects/event-scripts/alpha_user_onUpdate.js

fix when password hashing request is made

---

config/connectors/definitions/mongodb-companies-reduced-timeout.json
config/idm-endpoints/scripts-content/company.js

Extra connector

---

config/am-scripts/scripts-content/ch-callback-general-error.js
config/am-scripts/scripts-content/ch-callback-login-error.js
config/am-scripts/scripts-content/oidc-claims-script.groovy

removed logging

---

config/connectors/mappings/event-scripts/alphaUser_webfilingUser_onError.js
config/connectors/mappings/event-scripts/alphaUser_webfilingUser_onUpdate.js
config/connectors/mappings/event-scripts/chsMongoCompanyProfile_alphaOrg_onError.js
config/connectors/mappings/event-scripts/webfilingAuthCode_alphaOrg_onError.js
config/connectors/mappings/event-scripts/webfilingUser_alphaUser_onError.js

Changing error logging to debug where personal data is logged out

---

config/managed-objects/event-scripts/alpha_user_onUpdate.js

fix password hashing

---

config/idm-endpoints/scripts-content/companyauth.js

fix logging

---

config/auth-trees/ch-login.json

Chsa 29 (WIP)

---

config/am-scripts/scripts-content/ch-get-consent.js

added claims to pagePropJson

---

config/agents/remote-consent-agent.json.tpl
config/am-scripts/scripts-config.json
config/am-scripts/scripts-content/ch-consent-display-consent-response-success-url.js
config/auth-trees/ch-consent.json

fix for remote consent journey

---

config/am-scripts/scripts-content/ch-get-consent.js
config/am-scripts/scripts-content/ch-process-request-consent.js
config/applications/api-filing-m2m-client.json.tpl
config/applications/api-filing-web-client.json.tpl
config/applications/chs-internal-client.json.tpl

fix remote consent

---

config/am-scripts/scripts-config.json
config/am-scripts/scripts-content/oauth2-token-mod-apps.groovy
config/am-scripts/scripts-content/oauth2-token-mod.groovy
config/applications/api-filing-web-client.json.tpl
config/applications/chs-internal-client.json.tpl

Adding new OAuth2 token mod script for the API clients

---

config/agents/remote-consent-agent.json.tpl
config/am-scripts/scripts-config.json
config/am-scripts/scripts-content/ch-get-consent.js
config/am-scripts/scripts-content/oauth2-token-mod-apps.groovy
config/applications/api-filing-web-client.json.tpl
config/applications/chs-internal-client.json.tpl

various fixes

---

config/agents/remote-consent-agent.json.tpl

fix consent url

---

config/am-scripts/scripts-content/ch-get-consent.js

fix callbacks

---

config/connectors/definitions/mongodb-roles.json
config/connectors/definitions/mongodb-users.json
config/connectors/mappings/chsRoles_alphaRole.json
config/connectors/mappings/chsUsers_alphaUser.json

CHSA-85: Enable connections and mappings.

---

config/am-scripts/scripts-content/oauth2-token-mod-apps.groovy

Chsa 86 add roles to access token

---

config/connectors/definitions/mongodb-api-client-keys
config/idm-endpoints/scripts-config.json
config/idm-endpoints/scripts-content/migrate-web-key.js

web key migration script

---

config/applications/perf-test-client.json.tpl

perf test client

---

config/am-scripts/scripts-library/ch-library-functions.js

for loop syntax fix

---

config/connectors/definitions/webfiling-users.json

changes made to web-filinguser config

---

config/connectors/schedules/auth-codes.json
config/connectors/schedules/companies.json
config/connectors/schedules/users.json
scripts/update-connector-schedules.js

Updated the FIDC API endpoint in `scripts/update-connector-schedules.js` to use an endpoint that supports the use of ESVs in reconciliation schedule configuration.
Updated connector reconciliation schedules to define the appropriate ESVs

Set Schedule ESVs

---

tests/scripts/update-connector-schedules.test.js

Updates unit test for updated FIDC endpoint.

Update tests for new API endpoint

---

config/am-scripts/scripts-content/ch-callback-to-capture-otp-response.js

optimise initial modifications to login journey

refactor: optimise initial modifications to login journey

---

config/auth-trees/ch-multi-factor-generic.json
config/idm-endpoints/scripts-content/companies.js

Value is being passed as string instead of integer, breaking pagination logic. 

fix: change value from string to int to fix logic

---

config/idm-endpoints/scripts-content/company.js

added back in attribute that is used

IDAM-1611: added back in attribute that is used

---

config/idm-endpoints/scripts-content/company.js

IDAM-1611: removed unused attribute

---

config/idm-endpoints/scripts-content/companies.js

feat: paginate backend calls to db and create modular functions

---

config/idm-endpoints/scripts-content/companies.js

feat: add pagination to search

---

config/connectors/mappings/inactiveUser_alphaUser.json

improve inactive user query performance by using clustered recon

improve inactive user recon performance

---

config/am-scripts/scripts-content/ch-callback-to-capture-otp-response.js
config/am-scripts/scripts-content/ch-password-reset-text-sent.js
config/am-scripts/scripts-content/ch-registration-confirmation-email-sent.js
config/am-scripts/scripts-content/ch-registration-send-email.js
config/am-scripts/scripts-content/ch-send-mfa-email.js
config/am-scripts/scripts-content/ch-send-mfa-sms.js
config/applications/perf-test-client.json.tpl

Changes to assist load testing

Load testing

---

config/auth-trees/ch-update-password.json

fix: session vulnerability format correction

---

config/am-scripts/scripts-config.json
config/am-scripts/scripts-content/ch-invalidate-user-sessions.js
config/auth-trees/ch-update-password.json

fix: session vulnerability add script config

---

config/connectors/definitions/inactive-user.json
config/idm-endpoints/scripts-config.json
config/variables-secrets/secrets.json

Reverted last 3 commits due to failing pipeline

Revert changes

---

.env.sample
README.md
helpers/fidc-get.js
helpers/fidc-post.js
helpers/fidc-request.js
helpers/get-session-token.js
index.js
tests/helpers/fidc-get.test.js
tests/helpers/fidc-request.test.js
tests/helpers/get-session-token.test.js

The pipeline is currently failing due to an error retrieving a session token. It appears the process for getting a session token via the REST API has changed so the helper function needed to be updated. https://backstage.forgerock.com/docs/idcloud/latest/am-authentication/login-using-rest.html

fix: update get session token helper

---

config/connectors/remote-servers.json

Adds a new remote server to be used for exporting ForgeRock user data.

feat: add remote server for export

---

config/connectors/definitions/mongodb-forgerock-data.json
config/connectors/mappings/alphaUser_forgerockData.json

Added connector and mappings

---

config/connectors/mappings/alphaUser_forgerockData.json

Enabled export mapping

---

config/connectors/mappings/alphaUser_forgerockData.json

Enabled clustering

---

config/connectors/definitions/mongodb-forgerock-data.json
config/connectors/mappings/alphaUser_forgerockData.json

fix for missing date fields

---

config/am-scripts/scripts-content/ch-update-email-input-collector.js

Fix uppercase incident where users with capital letters in their email addresses cannot access WebFiling area.
Incident is logged in Envision, number [CS002060027](https://envision.service-now.com/now/nav/ui/classic/params/target/sn_customerservice_case.do%3Fsys_id%3D8e295af61b2682d4b96ca6c8ec4bcb2f%26sysparm_view%3Dcase%26sysparm_record_target%3Dsn_customerservice_case%26sysparm_record_row%3D1%26sysparm_record_rows%3D4%26sysparm_record_list%3Dactive%253Dtrue%255Ecompany%253D85584998dba8ce1822f41fba1396199c%255EORcompany%253D7011dd94db2cce1822f41fba13961906%255EORcompany%253D51f7b9681ba6e1941b84777e0a4bcb87%255EORcompany%253D396f52171b056d9cbaf5c918624bcb50%255EconsumerISEMPTY%255EORDERBYDESCsys_updated_on)
Fix consists in lowering the case of the email address entered by users in the …

fix: upper case incident

---

config/connectors/definitions/archived/mongodb-auth-code.json
config/connectors/definitions/archived/mongodb-roles.json
config/connectors/definitions/archived/mongodb-users.json
config/connectors/definitions/mongodb-companies.json
config/connectors/definitions/mongodb-forgerock-data.json

Back to MongoDB connector version 1.5.20.22, as this version has been made to work on Staging.

Edms922 reverse mongo connr

---

config/connectors/definitions/archived/mongodb-api-client-keys

Connectors client API keys file needed updating as well. 

fix: update mdb version on api keys file

---

config/connectors/definitions/webfiling-auth-test-code.json

This is part of the work regarding the RCS connector upgrade

RCS connector upgrade timeouts

---

config/connectors/definitions/webfiling-auth-test-code.json

Update webfiling-auth-test-code.json for connector changes

---

config/connectors/definitions/mongodb-companies.json
config/connectors/definitions/mongodb-forgerock-data.json

FIDC Update Required:
Updating Connector timeout as per recommendation from PING 
connectors / mappings / scheduled recons (IDM)

Operation timeout update

---

config/connectors/definitions/mongodb-companies.json
config/connectors/definitions/mongodb-forgerock-data.json

Updating the mongo db version as per the RCS connector update

---

.env.sample
config/agents/remote-consent-agent.json.tpl
config/applications/archived/api-filing-web-client.json.tpl
config/applications/archived/chs-internal-client.json.tpl
config/idm-endpoints/archived/migrate-web-key.js

- `idam-ui.amido.aws.chdev.org` -> `idam-ui-dev.company-information.service.gov.uk`
- `idam.amido.aws.chdev.org` -> `idam-dev.company-information.service.gov.uk`

Update hardcoded Dev URLs
